**Mini project on student Data using numpy only**

#Mini Project-

In [ ]:
import numpy as np

Q1-Create suitable arrays to represent students, subjects, and their marks

In [ ]:
std_dt=np.array([80,87,89,87,96,78,79,76,96,80,81,89])
std_dt

array([80, 87, 89, 87, 96, 78, 79, 76, 96, 80, 81, 89])

Q2-Explore the properties of these arrays - such a dimension, size , structure

In [ ]:
print(std_dt.ndim)
print(std_dt.size)
print(std_dt.shape)

1
12
(12,)


Q3-Perform necessary reshaping and reorganization of the data to suit various operations

In [ ]:
#Q3 reshaping data
arr2=std_dt.reshape((3,4))
arr2

array([[80, 87, 89, 87],
       [96, 78, 79, 76],
       [96, 80, 81, 89]])

Q4- Merge or split arrays to simulate adding nre students , new subjects,or organizing the dataset

In [ ]:
#Q4 adding data
new_d=np.array([67,87,97,73])

In [ ]:
#Q4 merging data
new_std_data=np.vstack((arr2,new_d))
new_std_data

array([[80, 87, 89, 87],
       [96, 78, 79, 76],
       [96, 80, 81, 89],
       [67, 87, 97, 73]])

Q5- Apply operations to update marks ,remove data, identity unique information

In [ ]:
#Q5 update marks
new_std_data[1,2]=87
new_std_data

array([[80, 87, 89, 87],
       [96, 78, 87, 76],
       [96, 80, 81, 89],
       [67, 87, 97, 73]])

In [ ]:
#Q5 Remove data
new_data=np.delete(new_std_data,4)
new_data

array([80, 87, 89, 87, 78, 87, 76, 96, 80, 81, 89, 67, 87, 97, 73])

In [ ]:
#Q5 unique data
unique_data=np.unique(new_data)
unique_data

array([67, 73, 76, 78, 80, 81, 87, 89, 96, 97])

Q6- Demonstrate how the same data can exist in different data types and how changes affect
Q7- Show the difference between creating a full copy of an array and creating a view of the same data

In [ ]:
#Q6 datatype changes
print(unique_data.dtype)

#Q7copy data
copied_marks=np.copy(unique_data)
print(copied_marks)
#Q6 changing the data type
copied_marks.astype(float)

int64
[67 73 76 78 80 81 87 89 96 97]


array([67., 73., 76., 78., 80., 81., 87., 89., 96., 97.])